@startuml
stateDiagram-v2
    [*] --> Cursando
    Cursando --> Aprovado: Média ≥ 6
    Cursando --> ProvaFinal: 4 ≤ Média < 6
    Cursando --> Reprovado: Média < 4
    ProvaFinal --> Aprovado: PF ≥ 6
    ProvaFinal --> Reprovado: PF < 6
@enduml
