@startuml
partition "Analise Estatica" {
  (SonarQube) : Bugs, Vulnerabilidades, Code Smells
  (Checkstyle) : Padroes de codificacao Java
  (pylint) : Erros e estilo Python
  (ESLint) : Padroes JavaScript
}
@enduml