mindmap
  root((Qualidade de Software))
    ISO 25010
      Adequação Funcional
      Eficiência de Desempenho
      Compatibilidade
      Usabilidade
      Confiabilidade
      Segurança
      Manutenibilidade
      Portabilidade
    Custos
      Regra 1:10:100
      Shift Left
    Processo
      Verificação
      Validação
    Normas
      CMMI
      MPS.BR
