mindmap
  root(ISO 25010)
    Adequação Funcional
      Completude
      Correção
      Pertinência
    Eficiência de Desempenho
      Comportamento temporal
      Utilização de recursos
      Capacidade
    Compatibilidade
      Coexistência
      Interoperabilidade
    Usabilidade
      Reconhecibilidade
      Apreensibilidade
      Operabilidade
    Confiabilidade
      Maturidade
      Disponibilidade
      Tolerância a falhas
    Segurança
      Confidencialidade
      Integridade
    Manutenibilidade
      Modularidade
      Reutilizabilidade
      Modificabilidade
    Portabilidade
      Adaptabilidade
      Instalabilidade
