version: '3.3'
services:
  # Default User: admin; Password: admin
  # docker exec -ti testlink sh -c 'chown www-data:www-data /var/testlink/*'
  # 2- Run installation sequence: https://testlink.localhost/install/
  # 2- Run installation sequence: http://localhost:8181/install
  testlink:
    image: gigashiro/testlink
    #build: 
    #  context: ./testlink
    container_name: testlink
    hostname: testlink 
    environment:
    - TZ=America/Sao_Paulo
    - DB_USER=testlink
    - DB_PASS=passw0rd
    - DB_HOST=mysql
    - DB_NAME=testlink
    restart: always
    volumes:
    - testlink-logs:/var/testlink/logs:rw
    - testlink-uploads:/var/testlink/upload_area:rw
    ports:
    - "80:80"
    dns:
    - ${IPV4_NETWORK:-172.23.1}.254
    - 8.8.8.8
    networks:
      goTestlink:
        aliases:
        - testlink

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql-testlink
    hostname: mysql
    environment:
    - TZ=America/Sao_Paulo
    - MYSQL_DATABASE=testlink
    - MYSQL_USER=testlink
    - MYSQL_PASSWORD=passw0rd
    - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
    - mysql-data:/var/lib/mysql
    dns:
    - ${IPV4_NETWORK:-172.23.1}.254
    - 8.8.8.8
    networks:
      goTestlink:
        aliases:
        - mysql

  postgresql:
    image: postgres:latest
    container_name: postgresql-testlink
    hostname: postgresql
    environment:
        - TZ=America/Sao_Paulo
        - POSTGRES_DB=testlink
        - POSTGRES_USER=testlink
        - POSTGRES_PASSWORD=passw0rd
    restart: always
    volumes:
        - postgres-data:/var/lib/postgresql/data
    dns:
        - ${IPV4_NETWORK:-172.23.1}.254
        - 8.8.8.8
    networks:
      goTestlink:
        aliases:
          - postgresql        

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-mantis
    hostname: portainer
    environment:
    - TZ=America/Sao_Paulo
    restart: always
    #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    #command: --templates http://templates/templates.json
    command: -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    ports:
    - "9000:9000"
    dns:
    - ${IPV4_NETWORK:-172.23.1}.254
    - 8.8.8.8
    networks:
      goTestlink:
        aliases:
        - portainer

networks:
    goTestlink:
       driver: bridge
       #enable_ipv6: true
       #name: goTestlink
       ipam:
          driver: default
          config:
          - subnet: ${IPV4_NETWORK:-172.23.1}.0/24
          #- subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
   mysql-data:
   testlink-logs:
   testlink-uploads:
   postgres-data:
